myapp:
  books:
    - title: "ajay"
      author: "F. Scott Fitzgerald"
      isbn: "9780141182636"
    - title: "To Kill a Mockingbird"
      author: "kumar"
      isbn: "9780446310789"
    - title: "1984"
      author: "George Orwell"
      isbn: "9780451524935"
spring:
  application:
    name: book-service
server:
  port: 9004
  
