server:
  port:
    9002
myapp:
  books:
    - title: "The Great Gatsby"
      author: "F. Scott Fitzgerald"
      isbn: "9780141182636"
    - title: "To Kill a Mockingbird"
      author: "Harper Lee"
      isbn: "9780446310789"
    - title: "1984"
      author: "George Orwell"
      isbn: "9780451524935"
spring:
  application:
    name: book-service
